name: Build and deploy site

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.3

      - name: Install markdown-to-html
        run: npm install markdown-to-html

      - name: Install markdown-to-html
        run: |
          wget https://raw.githubusercontent.com/ekalinin/github-markdown-toc/master/gh-md-toc
          chmod +x gh-md-toc

      - name: Build site
        run: |
          gh-mod-toc --insert README.md
          npx markdown README.md > index.html

      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  
          cname: organize.fyi
