name: Build and deploy site

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/install@v0.1
        with:
          crate: pulldown-cmark
          version: latest

      - name: Build site
        run: ./build-site

      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/
          cname: organize.fyi
