name: Build and deploy site

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.3

      - uses: actions-rs/install@v0.1
        with:
          crate: pulldown-cmark
          version: latest

      - name: Install markdown-to-html
        run: |
          wget https://raw.githubusercontent.com/ekalinin/github-markdown-toc/master/gh-md-toc
          chmod +x gh-md-toc

      - name: Build site
        run: |
          ./gh-md-toc --insert README.md
          pulldown-cmark <  README.md > index.html

      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          cname: organize.fyi
